### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct

### method
stage: pt
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 64

### dataset
dataset: pre_train
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/pre_train
logging_steps: 10
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 5.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
